spring:
  datasource:
    url: jdbc:mysql://mysql:3306/Hunter
    username: root
    password: root
    #password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  context-path: /api
  port: 8080


logging:
  level:
    org.springframework.security: INFO

security.oauth2.clientId: mobile
security.oauth2.secret: