app:
  version: @project.version@
  swagger:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/Hunter
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  redis:
    host: redis

server:
  servlet:
    context-path: /api
  port: 8080

logging:
  level:
    org.springframework.security: INFO
